# Generated by Django 5.1.6 on 2025-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('SubtaskId', models.AutoField(primary_key=True, serialize=False)),
                ('SubtaskDescription', models.CharField(max_length=500)),
                ('SubtaskStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskDescription', models.CharField(max_length=500)),
                ('TaskStatus', models.CharField(max_length=500)),
                ('TaskCreationDate', models.DateField()),
            ],
        ),
    ]
